# Generated by Django 5.0.4 on 2024-04-11 02:49

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('asian', 'asian'), ('american', 'american'), ('mexican', 'mexican'), ('italian', 'italian'), ('french', 'french'), ('egyptian', 'egyptian'), ('morrocan', 'morrocan'), ('indian', 'indian'), ('chinese', 'chinese'), ('japanese', 'japanese'), ('other', 'other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='recipe_images/default.jpg', upload_to='recipe_images'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=ckeditor.fields.RichTextField(default='Write your ingredients here...'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=ckeditor.fields.RichTextField(default='Write your instructions here...'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_cook_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='Enter the name of your dish...', max_length=100),
        ),
    ]
